using IksOks.Web.Contracts.Matches;

public sealed record MatchDetailsResponse(
    Guid Id,
    Guid OwnerUserId,
    string OwnerUserName,
    Guid? OpponentUserId,
    string? OpponentUserName,
    string Mode,
    int BoardSize,
    int WinLength,
    string Status,
    Guid? PauseRequestedByUserId,
    string? PauseRequestedByUserName,
    DateTimeOffset? PauseRequestedAt,
    Guid? ResumeRequestedByUserId,
    string? ResumeRequestedByUserName,
    DateTimeOffset? ResumeRequestedAt,
    int TurnDurationSeconds,
    DateTimeOffset? TurnDeadlineAt,
    Guid? CurrentTurnUserId,
    Guid? WinnerUserId,
    string? WinnerUserName,
    DateTimeOffset CreatedAt,
    DateTimeOffset? FinishedAt,
    IReadOnlyList<MoveResponse> Moves);